#!/bin/bash

##Example for Darwin in Cambridge (adapted from STG python)

#SBATCH -p sandybridge
#SBATCH -A PLANCK
#SBATCH --nodes=##NUMNODES##
#SBATCH --ntasks=##NUMMPI##
#SBATCH --time=##WALLTIME##
#SBATCH --mail-type=FAIL
#SBATCH --mem=##MEM_MB##

cd ##ROOTDIR##

. /etc/profile.d/modules.sh
module purge
module load default-impi
module load cfitsio


echo Running on host \`hostname\`
echo Time is \`date\`
echo Directory is \`pwd\`
echo Slurm job ID is \$SLURM_JOBID
echo This jobs runs on the following machines:
export NODEFILE=`generate_pbs_nodefile`
echo \`cat \$NODEFILE | uniq\`

cat \$NODEFILE | uniq > scripts/machine.file.\$SLURM_JOBID

export OMP_NUM_THREADS=$omp
export I_MPI_PIN_DOMAIN=omp:compact
export I_MPI_PIN_ORDER=scatter
export I_MPI_CPUINFO=proc

##COMMAND##


